"""add demand calculation schema

Revision ID: 20260723_03
Revises: cdbae5051f35
Create Date: 2026-07-23 14:14:27.076492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260723_03'
down_revision: Union[str, None] = 'cdbae5051f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_scenario_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_scenario_templates_code'), 'demand_scenario_templates', ['code'], unique=True)
    op.create_index(op.f('ix_demand_scenario_templates_is_active'), 'demand_scenario_templates', ['is_active'], unique=False)
    op.create_table('demand_scenario_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_template_id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=64), nullable=False),
    sa.Column('version_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'RETIRED', name='scenarioversionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('default_service_level', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('criticality_service_levels_json', sa.JSON(), nullable=False),
    sa.Column('missing_parameter_policy', sa.Enum('STRICT', 'WARN_AND_SKIP', 'FALLBACK', name='missingparameterpolicy', native_enum=False, length=24), nullable=False),
    sa.Column('execution_mode', sa.Enum('AUTO', 'ANALYTICAL', 'MONTE_CARLO', 'COMPARE', name='demandexecutionmode', native_enum=False, length=20), nullable=False),
    sa.Column('comparison_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_initial_age_hours', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('default_repair_parameters_json', sa.JSON(), nullable=True),
    sa.Column('fallback_parameters_json', sa.JSON(), nullable=True),
    sa.Column('simulation_config_json', sa.JSON(), nullable=False),
    sa.Column('formula_version', sa.String(length=64), nullable=False),
    sa.Column('input_schema_version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_initial_age_hours >= 0', name='ck_demand_default_age_nonnegative'),
    sa.CheckConstraint('default_service_level > 0 AND default_service_level < 1', name='ck_demand_default_service_level'),
    sa.ForeignKeyConstraint(['scenario_template_id'], ['demand_scenario_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_template_id', 'version_code', name='uq_demand_scenario_version')
    )
    op.create_index(op.f('ix_demand_scenario_versions_scenario_template_id'), 'demand_scenario_versions', ['scenario_template_id'], unique=False)
    op.create_index(op.f('ix_demand_scenario_versions_status'), 'demand_scenario_versions', ['status'], unique=False)
    op.create_table('demand_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_code', sa.String(length=64), nullable=False),
    sa.Column('calculation_name', sa.String(length=200), nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=True),
    sa.Column('source_calculation_id', sa.Integer(), nullable=True),
    sa.Column('rerun_mode', sa.Enum('NEW', 'REPLAY_SNAPSHOT', 'RERUN_LATEST', name='rerunmode', native_enum=False, length=24), nullable=False),
    sa.Column('execution_type', sa.Enum('SYNCHRONOUS', 'ASYNCHRONOUS', name='calculationexecutiontype', native_enum=False, length=20), nullable=False),
    sa.Column('requested_mode', sa.Enum('AUTO', 'ANALYTICAL', 'MONTE_CARLO', 'COMPARE', name='demandexecutionmode', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED', 'INTERRUPTED', name='calculationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_stage', sa.String(length=200), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('inventory_snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_demand_calculation_progress'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['demand_scenario_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_calculation_id'], ['demand_calculations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_calculations_calculation_code'), 'demand_calculations', ['calculation_code'], unique=True)
    op.create_index(op.f('ix_demand_calculations_idempotency_key'), 'demand_calculations', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_demand_calculations_input_snapshot_hash'), 'demand_calculations', ['input_snapshot_hash'], unique=False)
    op.create_index(op.f('ix_demand_calculations_scenario_version_id'), 'demand_calculations', ['scenario_version_id'], unique=False)
    op.create_index(op.f('ix_demand_calculations_source_calculation_id'), 'demand_calculations', ['source_calculation_id'], unique=False)
    op.create_index(op.f('ix_demand_calculations_status'), 'demand_calculations', ['status'], unique=False)
    op.create_table('demand_fleet_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('default_initial_age_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_initial_age_hours IS NULL OR default_initial_age_hours >= 0', name='ck_demand_fleet_age'),
    sa.CheckConstraint('initial_quantity > 0', name='ck_demand_fleet_quantity'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['demand_scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_version_id', 'group_code', name='uq_demand_fleet_group_code')
    )
    op.create_index(op.f('ix_demand_fleet_groups_configuration_version_id'), 'demand_fleet_groups', ['configuration_version_id'], unique=False)
    op.create_index(op.f('ix_demand_fleet_groups_scenario_version_id'), 'demand_fleet_groups', ['scenario_version_id'], unique=False)
    op.create_table('demand_scenario_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=64), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('utilization_rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('mission_intensity_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('environment_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('temperature_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('dust_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('humidity_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('vibration_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('maintenance_level', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_hours > 0', name='ck_demand_stage_duration'),
    sa.CheckConstraint('stage_order >= 1', name='ck_demand_stage_order'),
    sa.CheckConstraint('utilization_rate >= 0 AND utilization_rate <= 1', name='ck_demand_stage_utilization'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['demand_scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_version_id', 'stage_code', name='uq_demand_stage_code'),
    sa.UniqueConstraint('scenario_version_id', 'stage_order', name='uq_demand_stage_order')
    )
    op.create_index(op.f('ix_demand_scenario_stages_scenario_version_id'), 'demand_scenario_stages', ['scenario_version_id'], unique=False)
    op.create_table('repair_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_code', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=200), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_level', sa.String(length=64), nullable=True),
    sa.Column('repair_success_rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('condemnation_rate', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('repair_turnaround_hours', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('turnaround_std_hours', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('initial_repair_pipeline_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('data_source_type', sa.Enum('DESIGN_PARAMETER', 'MAINTENANCE_RECORD', 'TEST_DATA', 'MANUAL_ESTIMATE', 'LITERATURE', 'EXPERT_JUDGMENT', name='datasourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('data_source_reference', sa.String(length=500), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('condemnation_rate >= 0 AND condemnation_rate <= 1', name='ck_repair_condemnation_rate'),
    sa.CheckConstraint('confidence_level IS NULL OR (confidence_level > 0 AND confidence_level <= 1)', name='ck_repair_confidence'),
    sa.CheckConstraint('initial_repair_pipeline_quantity >= 0', name='ck_repair_initial_pipeline_nonnegative'),
    sa.CheckConstraint('repair_success_rate + condemnation_rate <= 1', name='ck_repair_probability_sum'),
    sa.CheckConstraint('repair_success_rate >= 0 AND repair_success_rate <= 1', name='ck_repair_success_rate'),
    sa.CheckConstraint('repair_turnaround_hours > 0', name='ck_repair_turnaround_positive'),
    sa.CheckConstraint('sample_size IS NULL OR sample_size >= 0', name='ck_repair_sample_size_nonnegative'),
    sa.CheckConstraint('turnaround_std_hours >= 0', name='ck_repair_std_nonnegative'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='ck_repair_date_order'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_profiles_configuration_version_id'), 'repair_profiles', ['configuration_version_id'], unique=False)
    op.create_index(op.f('ix_repair_profiles_is_active'), 'repair_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_repair_profiles_maintenance_level'), 'repair_profiles', ['maintenance_level'], unique=False)
    op.create_index(op.f('ix_repair_profiles_profile_code'), 'repair_profiles', ['profile_code'], unique=True)
    op.create_index(op.f('ix_repair_profiles_spare_part_id'), 'repair_profiles', ['spare_part_id'], unique=False)
    op.create_table('demand_age_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fleet_group_id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('distribution_type', sa.Enum('FIXED', 'UNIFORM', 'NORMAL', 'TRIANGULAR', name='agedistributiontype', native_enum=False, length=20), nullable=False),
    sa.Column('proportion', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('fixed_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('minimum_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('maximum_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('mean_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('std_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('mode_hours', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('proportion > 0 AND proportion <= 1', name='ck_demand_age_proportion'),
    sa.CheckConstraint('sort_order >= 0', name='ck_demand_age_sort'),
    sa.ForeignKeyConstraint(['fleet_group_id'], ['demand_fleet_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_group_id', 'group_code', name='uq_demand_age_group_code')
    )
    op.create_index(op.f('ix_demand_age_groups_fleet_group_id'), 'demand_age_groups', ['fleet_group_id'], unique=False)
    op.create_table('demand_calculation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('run_mode', sa.Enum('AUTO', 'ANALYTICAL', 'MONTE_CARLO', 'COMPARE', name='demandexecutionmode', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED', 'INTERRUPTED', name='calculationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('previous_run_id', sa.Integer(), nullable=True),
    sa.Column('is_current_attempt', sa.Boolean(), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_stage_code', sa.String(length=64), nullable=True),
    sa.Column('completed_batches', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('formula_version', sa.String(length=64), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('simulation_config_json', sa.JSON(), nullable=True),
    sa.Column('actual_simulation_runs', sa.Integer(), nullable=True),
    sa.Column('converged', sa.Boolean(), nullable=True),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('convergence_metrics_json', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_demand_run_attempt'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_demand_run_progress'),
    sa.ForeignKeyConstraint(['calculation_id'], ['demand_calculations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_run_id'], ['demand_calculation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_id', 'run_mode', 'attempt_number', name='uq_demand_run_attempt')
    )
    op.create_index(op.f('ix_demand_calculation_runs_calculation_id'), 'demand_calculation_runs', ['calculation_id'], unique=False)
    op.create_table('demand_common_shock_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('shock_code', sa.String(length=64), nullable=False),
    sa.Column('shock_name', sa.String(length=200), nullable=False),
    sa.Column('probability', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('application_mode', sa.Enum('FAILURE_RATE', 'FAILURE_PROBABILITY', 'EQUIVALENT_AGE', name='shockapplicationmode', native_enum=False, length=32), nullable=False),
    sa.Column('fleet_group_id', sa.Integer(), nullable=True),
    sa.Column('affected_criticality_json', sa.JSON(), nullable=True),
    sa.Column('affected_categories_json', sa.JSON(), nullable=True),
    sa.Column('affected_spare_parts_json', sa.JSON(), nullable=True),
    sa.Column('maximum_occurrences', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('maximum_occurrences >= 1', name='ck_demand_shock_occurrences'),
    sa.CheckConstraint('multiplier > 0', name='ck_demand_shock_multiplier'),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_demand_shock_probability'),
    sa.ForeignKeyConstraint(['fleet_group_id'], ['demand_fleet_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['demand_scenario_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'shock_code', name='uq_demand_shock_code')
    )
    op.create_index(op.f('ix_demand_common_shock_rules_fleet_group_id'), 'demand_common_shock_rules', ['fleet_group_id'], unique=False)
    op.create_index(op.f('ix_demand_common_shock_rules_stage_id'), 'demand_common_shock_rules', ['stage_id'], unique=False)
    op.create_table('demand_parameter_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_version_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('fleet_group_id', sa.Integer(), nullable=True),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('reliability_profile_id', sa.Integer(), nullable=True),
    sa.Column('repair_profile_id', sa.Integer(), nullable=True),
    sa.Column('model_type_override', sa.String(length=32), nullable=True),
    sa.Column('failure_process_mode', sa.Enum('AUTO', 'SINGLE_FAILURE', 'RENEWAL', 'COUNT_DISTRIBUTION', name='failureprocessmode', native_enum=False, length=32), nullable=False),
    sa.Column('service_level_override', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('exclude_from_calculation', sa.Boolean(), nullable=False),
    sa.Column('reliability_parameters_json', sa.JSON(), nullable=True),
    sa.Column('repair_parameters_json', sa.JSON(), nullable=True),
    sa.Column('adjustment_factors_json', sa.JSON(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('service_level_override IS NULL OR (service_level_override > 0 AND service_level_override < 1)', name='ck_demand_override_service_level'),
    sa.ForeignKeyConstraint(['fleet_group_id'], ['demand_fleet_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reliability_profile_id'], ['reliability_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repair_profile_id'], ['repair_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['demand_scenario_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['demand_scenario_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_version_id', 'stage_id', 'fleet_group_id', 'spare_part_id', name='uq_demand_override_scope')
    )
    op.create_index(op.f('ix_demand_parameter_overrides_fleet_group_id'), 'demand_parameter_overrides', ['fleet_group_id'], unique=False)
    op.create_index(op.f('ix_demand_parameter_overrides_scenario_version_id'), 'demand_parameter_overrides', ['scenario_version_id'], unique=False)
    op.create_index(op.f('ix_demand_parameter_overrides_spare_part_id'), 'demand_parameter_overrides', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_demand_parameter_overrides_stage_id'), 'demand_parameter_overrides', ['stage_id'], unique=False)
    op.create_table('demand_stage_fleet_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('fleet_group_id', sa.Integer(), nullable=False),
    sa.Column('active_quantity', sa.Integer(), nullable=False),
    sa.Column('utilization_override', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('equipment_intensity_factor', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('environment_factor_override', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('active_quantity >= 0', name='ck_demand_active_quantity'),
    sa.ForeignKeyConstraint(['fleet_group_id'], ['demand_fleet_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['demand_scenario_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'fleet_group_id', name='uq_demand_stage_fleet_usage')
    )
    op.create_index(op.f('ix_demand_stage_fleet_usages_fleet_group_id'), 'demand_stage_fleet_usages', ['fleet_group_id'], unique=False)
    op.create_index(op.f('ix_demand_stage_fleet_usages_is_active'), 'demand_stage_fleet_usages', ['is_active'], unique=False)
    op.create_index(op.f('ix_demand_stage_fleet_usages_stage_id'), 'demand_stage_fleet_usages', ['stage_id'], unique=False)
    op.create_table('demand_run_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('stage_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('stage_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('fleet_group_id', sa.Integer(), nullable=True),
    sa.Column('fleet_group_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('configuration_version_id', sa.Integer(), nullable=True),
    sa.Column('configuration_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('configuration_item_id', sa.Integer(), nullable=True),
    sa.Column('item_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('position_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('part_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('install_quantity_snapshot', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('equipment_quantity_snapshot', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('replacement_ratio_snapshot', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('expected_failure_contribution', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_replacement_contribution', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('net_consumption_contribution', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('repair_pipeline_contribution', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('common_shock_contribution', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('reliability_parameter_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('repair_parameter_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('adjustment_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('selection_reason_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['demand_calculation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configuration_item_id'], ['configuration_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fleet_group_id'], ['demand_fleet_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['demand_scenario_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_run_contributions_calculation_run_id'), 'demand_run_contributions', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_demand_run_contributions_fleet_group_id'), 'demand_run_contributions', ['fleet_group_id'], unique=False)
    op.create_index(op.f('ix_demand_run_contributions_spare_part_id'), 'demand_run_contributions', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_demand_run_contributions_stage_id'), 'demand_run_contributions', ['stage_id'], unique=False)
    op.create_table('demand_run_item_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_code_snapshot', sa.String(length=64), nullable=False),
    sa.Column('spare_part_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('criticality_level', sa.String(length=20), nullable=True),
    sa.Column('calculation_status', sa.Enum('CALCULATED', 'SKIPPED', 'FALLBACK', name='itemcalculationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('selected_model_type', sa.Enum('EXPONENTIAL', 'WEIBULL', 'BINOMIAL', 'NEGATIVE_BINOMIAL', 'EMPIRICAL', name='reliabilitymodeltype', native_enum=False, length=32), nullable=True),
    sa.Column('failure_process_mode', sa.Enum('AUTO', 'SINGLE_FAILURE', 'RENEWAL', 'COUNT_DISTRIBUTION', name='failureprocessmode', native_enum=False, length=32), nullable=False),
    sa.Column('selected_reliability_profile_id', sa.Integer(), nullable=True),
    sa.Column('selected_repair_profile_id', sa.Integer(), nullable=True),
    sa.Column('selection_reason_json', sa.JSON(), nullable=True),
    sa.Column('parameter_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('is_manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('target_service_level', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('expected_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('variance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('standard_deviation', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('p50', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('p80', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('p90', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('p95', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('p99', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('target_quantile_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_replacement_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('repair_pipeline_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('repair_pipeline_peak', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('net_consumption_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('recommended_spare_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('on_hand_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('in_transit_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('safety_stock_reserved', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('usable_inventory', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('net_demand_gap', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('inventory_coverage_rate', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('shortage_risk_level', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='shortagerisklevel', native_enum=False, length=20), nullable=False),
    sa.Column('minimum_inventory_point', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('maximum_simultaneous_gap', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('common_shock_demand', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('warning_codes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['demand_calculation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_reliability_profile_id'], ['reliability_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_repair_profile_id'], ['repair_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_run_id', 'spare_part_id', name='uq_demand_run_item')
    )
    op.create_index(op.f('ix_demand_run_item_results_calculation_run_id'), 'demand_run_item_results', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_demand_run_item_results_spare_part_id'), 'demand_run_item_results', ['spare_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demand_run_item_results_spare_part_id'), table_name='demand_run_item_results')
    op.drop_index(op.f('ix_demand_run_item_results_calculation_run_id'), table_name='demand_run_item_results')
    op.drop_table('demand_run_item_results')
    op.drop_index(op.f('ix_demand_run_contributions_stage_id'), table_name='demand_run_contributions')
    op.drop_index(op.f('ix_demand_run_contributions_spare_part_id'), table_name='demand_run_contributions')
    op.drop_index(op.f('ix_demand_run_contributions_fleet_group_id'), table_name='demand_run_contributions')
    op.drop_index(op.f('ix_demand_run_contributions_calculation_run_id'), table_name='demand_run_contributions')
    op.drop_table('demand_run_contributions')
    op.drop_index(op.f('ix_demand_stage_fleet_usages_stage_id'), table_name='demand_stage_fleet_usages')
    op.drop_index(op.f('ix_demand_stage_fleet_usages_is_active'), table_name='demand_stage_fleet_usages')
    op.drop_index(op.f('ix_demand_stage_fleet_usages_fleet_group_id'), table_name='demand_stage_fleet_usages')
    op.drop_table('demand_stage_fleet_usages')
    op.drop_index(op.f('ix_demand_parameter_overrides_stage_id'), table_name='demand_parameter_overrides')
    op.drop_index(op.f('ix_demand_parameter_overrides_spare_part_id'), table_name='demand_parameter_overrides')
    op.drop_index(op.f('ix_demand_parameter_overrides_scenario_version_id'), table_name='demand_parameter_overrides')
    op.drop_index(op.f('ix_demand_parameter_overrides_fleet_group_id'), table_name='demand_parameter_overrides')
    op.drop_table('demand_parameter_overrides')
    op.drop_index(op.f('ix_demand_common_shock_rules_stage_id'), table_name='demand_common_shock_rules')
    op.drop_index(op.f('ix_demand_common_shock_rules_fleet_group_id'), table_name='demand_common_shock_rules')
    op.drop_table('demand_common_shock_rules')
    op.drop_index(op.f('ix_demand_calculation_runs_calculation_id'), table_name='demand_calculation_runs')
    op.drop_table('demand_calculation_runs')
    op.drop_index(op.f('ix_demand_age_groups_fleet_group_id'), table_name='demand_age_groups')
    op.drop_table('demand_age_groups')
    op.drop_index(op.f('ix_repair_profiles_spare_part_id'), table_name='repair_profiles')
    op.drop_index(op.f('ix_repair_profiles_profile_code'), table_name='repair_profiles')
    op.drop_index(op.f('ix_repair_profiles_maintenance_level'), table_name='repair_profiles')
    op.drop_index(op.f('ix_repair_profiles_is_active'), table_name='repair_profiles')
    op.drop_index(op.f('ix_repair_profiles_configuration_version_id'), table_name='repair_profiles')
    op.drop_table('repair_profiles')
    op.drop_index(op.f('ix_demand_scenario_stages_scenario_version_id'), table_name='demand_scenario_stages')
    op.drop_table('demand_scenario_stages')
    op.drop_index(op.f('ix_demand_fleet_groups_scenario_version_id'), table_name='demand_fleet_groups')
    op.drop_index(op.f('ix_demand_fleet_groups_configuration_version_id'), table_name='demand_fleet_groups')
    op.drop_table('demand_fleet_groups')
    op.drop_index(op.f('ix_demand_calculations_status'), table_name='demand_calculations')
    op.drop_index(op.f('ix_demand_calculations_source_calculation_id'), table_name='demand_calculations')
    op.drop_index(op.f('ix_demand_calculations_scenario_version_id'), table_name='demand_calculations')
    op.drop_index(op.f('ix_demand_calculations_input_snapshot_hash'), table_name='demand_calculations')
    op.drop_index(op.f('ix_demand_calculations_idempotency_key'), table_name='demand_calculations')
    op.drop_index(op.f('ix_demand_calculations_calculation_code'), table_name='demand_calculations')
    op.drop_table('demand_calculations')
    op.drop_index(op.f('ix_demand_scenario_versions_status'), table_name='demand_scenario_versions')
    op.drop_index(op.f('ix_demand_scenario_versions_scenario_template_id'), table_name='demand_scenario_versions')
    op.drop_table('demand_scenario_versions')
    op.drop_index(op.f('ix_demand_scenario_templates_is_active'), table_name='demand_scenario_templates')
    op.drop_index(op.f('ix_demand_scenario_templates_code'), table_name='demand_scenario_templates')
    op.drop_table('demand_scenario_templates')
    # ### end Alembic commands ###
