"""create master data schema

Revision ID: cdbae5051f35
Revises: 
Create Date: 2026-07-23 09:26:48.665904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cdbae5051f35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_series', sa.String(length=100), nullable=True),
    sa.Column('service_life_years', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('service_life_years IS NULL OR service_life_years >= 0', name='ck_equipment_service_life_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_models_code'), 'equipment_models', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_models_is_active'), 'equipment_models', ['is_active'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_type', sa.String(length=100), nullable=True),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=True),
    sa.Column('maintenance_level', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_code'), 'parts', ['code'], unique=True)
    op.create_index(op.f('ix_parts_is_active'), 'parts', ['is_active'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('material_code', sa.String(length=100), nullable=True),
    sa.Column('national_standard', sa.String(length=100), nullable=True),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('is_serialized', sa.Boolean(), nullable=False),
    sa.Column('is_repairable', sa.Boolean(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('default_service_level', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_service_level IS NULL OR (default_service_level > 0 AND default_service_level <= 1)', name='ck_spare_default_service_level'),
    sa.CheckConstraint('shelf_life_months IS NULL OR shelf_life_months >= 0', name='ck_spare_shelf_life_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_code'), 'spare_parts', ['code'], unique=True)
    op.create_index(op.f('ix_spare_parts_is_active'), 'spare_parts', ['is_active'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('supplier_type', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('credit_code', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qualification_status', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 100)', name='ck_supplier_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('responsible_person', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'FROZEN', 'COUNTING', name='warehousestatus', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_is_active'), 'warehouses', ['is_active'], unique=False)
    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_model_id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=64), nullable=False),
    sa.Column('version_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'RETIRED', name='configurationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR effective_date IS NULL OR expiry_date > effective_date', name='ck_configuration_date_order'),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_model_id', 'version_code', name='uq_configuration_equipment_version')
    )
    op.create_index(op.f('ix_configuration_versions_equipment_model_id'), 'configuration_versions', ['equipment_model_id'], unique=False)
    op.create_index(op.f('ix_configuration_versions_is_active'), 'configuration_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_configuration_versions_status'), 'configuration_versions', ['status'], unique=False)
    op.create_index('uq_configuration_active_default', 'configuration_versions', ['equipment_model_id'], unique=True, sqlite_where=sa.text("is_default = 1 AND is_active = 1 AND status = 'PUBLISHED'"), postgresql_where=sa.text("is_default IS TRUE AND is_active IS TRUE AND status = 'PUBLISHED'"))
    op.create_table('supplier_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_code', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_includes_tax', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('maximum_supply_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('quality_level', sa.String(length=100), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_offer_lead_time_nonnegative'),
    sa.CheckConstraint('maximum_supply_quantity IS NULL OR maximum_supply_quantity >= 0', name='ck_offer_max_supply_nonnegative'),
    sa.CheckConstraint('minimum_order_quantity >= 0', name='ck_offer_min_order_nonnegative'),
    sa.CheckConstraint('order_multiple > 0', name='ck_offer_order_multiple_positive'),
    sa.CheckConstraint('tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 1)', name='ck_offer_tax_rate'),
    sa.CheckConstraint('unit_price >= 0', name='ck_offer_price_nonnegative'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='ck_offer_date_order'),
    sa.CheckConstraint('warranty_months IS NULL OR warranty_months >= 0', name='ck_offer_warranty_nonnegative'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_offers_is_active'), 'supplier_offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplier_offers_offer_code'), 'supplier_offers', ['offer_code'], unique=True)
    op.create_index(op.f('ix_supplier_offers_spare_part_id'), 'supplier_offers', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_id'), 'supplier_offers', ['supplier_id'], unique=False)
    op.create_table('warehouse_inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('damaged_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quarantined_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('in_transit_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('maximum_stock', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('damaged_quantity >= 0', name='ck_inventory_damaged_nonnegative'),
    sa.CheckConstraint('in_transit_quantity >= 0', name='ck_inventory_in_transit_nonnegative'),
    sa.CheckConstraint('maximum_stock IS NULL OR maximum_stock >= 0', name='ck_inventory_max_nonnegative'),
    sa.CheckConstraint('maximum_stock IS NULL OR maximum_stock >= reorder_point', name='ck_inventory_max_ge_reorder'),
    sa.CheckConstraint('on_hand_quantity >= 0', name='ck_inventory_on_hand_nonnegative'),
    sa.CheckConstraint('quarantined_quantity >= 0', name='ck_inventory_quarantined_nonnegative'),
    sa.CheckConstraint('reorder_point >= 0', name='ck_inventory_reorder_nonnegative'),
    sa.CheckConstraint('reorder_point >= safety_stock', name='ck_inventory_reorder_ge_safety'),
    sa.CheckConstraint('reserved_quantity + damaged_quantity + quarantined_quantity <= on_hand_quantity', name='ck_inventory_allocated_not_exceed_on_hand'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_nonnegative'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_inventory_safety_nonnegative'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'spare_part_id', name='uq_inventory_warehouse_spare')
    )
    op.create_index(op.f('ix_warehouse_inventories_spare_part_id'), 'warehouse_inventories', ['spare_part_id'], unique=False)
    op.create_index(op.f('ix_warehouse_inventories_warehouse_id'), 'warehouse_inventories', ['warehouse_id'], unique=False)
    op.create_table('configuration_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=True),
    sa.Column('install_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('position_code', sa.String(length=100), nullable=True),
    sa.Column('position_name', sa.String(length=200), nullable=True),
    sa.Column('criticality_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticalitylevel', native_enum=False, length=20), nullable=False),
    sa.Column('replacement_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('maintenance_level', sa.String(length=64), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('install_quantity > 0', name='ck_configuration_install_quantity_positive'),
    sa.CheckConstraint('parent_item_id IS NULL OR parent_item_id != id', name='ck_item_not_self_parent'),
    sa.CheckConstraint('replacement_ratio >= 0 AND replacement_ratio <= 1', name='ck_configuration_replacement_ratio'),
    sa.CheckConstraint('sort_order >= 0', name='ck_configuration_sort_order_nonnegative'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['configuration_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_version_id', 'item_code', name='uq_configuration_item_code')
    )
    op.create_index(op.f('ix_configuration_items_configuration_version_id'), 'configuration_items', ['configuration_version_id'], unique=False)
    op.create_index(op.f('ix_configuration_items_parent_item_id'), 'configuration_items', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_configuration_items_part_id'), 'configuration_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_configuration_items_spare_part_id'), 'configuration_items', ['spare_part_id'], unique=False)
    op.create_table('reliability_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_code', sa.String(length=64), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.Enum('EXPONENTIAL', 'WEIBULL', 'BINOMIAL', 'NEGATIVE_BINOMIAL', 'EMPIRICAL', name='reliabilitymodeltype', native_enum=False, length=32), nullable=False),
    sa.Column('failure_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('mtbf_hours', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('weibull_shape', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('weibull_scale', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('binomial_trials', sa.Integer(), nullable=True),
    sa.Column('binomial_probability', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('negative_binomial_r', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('negative_binomial_p', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('empirical_mean', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('empirical_variance', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('extension_parameters_json', sa.JSON(), nullable=True),
    sa.Column('operating_condition_json', sa.JSON(), nullable=True),
    sa.Column('data_source_type', sa.Enum('DESIGN_PARAMETER', 'MAINTENANCE_RECORD', 'TEST_DATA', 'MANUAL_ESTIMATE', 'LITERATURE', 'EXPERT_JUDGMENT', name='datasourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('data_source_reference', sa.String(length=500), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('estimated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('binomial_probability IS NULL OR (binomial_probability >= 0 AND binomial_probability <= 1)', name='ck_reliability_binomial_probability'),
    sa.CheckConstraint('binomial_trials IS NULL OR binomial_trials > 0', name='ck_reliability_binomial_trials'),
    sa.CheckConstraint('confidence_level IS NULL OR (confidence_level > 0 AND confidence_level <= 1)', name='ck_reliability_confidence'),
    sa.CheckConstraint('empirical_mean IS NULL OR empirical_mean >= 0', name='ck_reliability_empirical_mean'),
    sa.CheckConstraint('empirical_variance IS NULL OR empirical_variance >= 0', name='ck_reliability_empirical_variance'),
    sa.CheckConstraint('failure_rate IS NULL OR failure_rate > 0', name='ck_reliability_failure_rate'),
    sa.CheckConstraint('mtbf_hours IS NULL OR mtbf_hours > 0', name='ck_reliability_mtbf'),
    sa.CheckConstraint('negative_binomial_p IS NULL OR (negative_binomial_p > 0 AND negative_binomial_p <= 1)', name='ck_reliability_negative_p'),
    sa.CheckConstraint('negative_binomial_r IS NULL OR negative_binomial_r > 0', name='ck_reliability_negative_r'),
    sa.CheckConstraint('sample_size IS NULL OR sample_size >= 0', name='ck_reliability_sample_size'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='ck_reliability_date_order'),
    sa.CheckConstraint('weibull_scale IS NULL OR weibull_scale > 0', name='ck_reliability_weibull_scale'),
    sa.CheckConstraint('weibull_shape IS NULL OR weibull_shape > 0', name='ck_reliability_weibull_shape'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reliability_profiles_configuration_version_id'), 'reliability_profiles', ['configuration_version_id'], unique=False)
    op.create_index(op.f('ix_reliability_profiles_is_active'), 'reliability_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_reliability_profiles_model_type'), 'reliability_profiles', ['model_type'], unique=False)
    op.create_index(op.f('ix_reliability_profiles_profile_code'), 'reliability_profiles', ['profile_code'], unique=True)
    op.create_index(op.f('ix_reliability_profiles_spare_part_id'), 'reliability_profiles', ['spare_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reliability_profiles_spare_part_id'), table_name='reliability_profiles')
    op.drop_index(op.f('ix_reliability_profiles_profile_code'), table_name='reliability_profiles')
    op.drop_index(op.f('ix_reliability_profiles_model_type'), table_name='reliability_profiles')
    op.drop_index(op.f('ix_reliability_profiles_is_active'), table_name='reliability_profiles')
    op.drop_index(op.f('ix_reliability_profiles_configuration_version_id'), table_name='reliability_profiles')
    op.drop_table('reliability_profiles')
    op.drop_index(op.f('ix_configuration_items_spare_part_id'), table_name='configuration_items')
    op.drop_index(op.f('ix_configuration_items_part_id'), table_name='configuration_items')
    op.drop_index(op.f('ix_configuration_items_parent_item_id'), table_name='configuration_items')
    op.drop_index(op.f('ix_configuration_items_configuration_version_id'), table_name='configuration_items')
    op.drop_table('configuration_items')
    op.drop_index(op.f('ix_warehouse_inventories_warehouse_id'), table_name='warehouse_inventories')
    op.drop_index(op.f('ix_warehouse_inventories_spare_part_id'), table_name='warehouse_inventories')
    op.drop_table('warehouse_inventories')
    op.drop_index(op.f('ix_supplier_offers_supplier_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_spare_part_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_offer_code'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_is_active'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_index('uq_configuration_active_default', table_name='configuration_versions', sqlite_where=sa.text("is_default = 1 AND is_active = 1 AND status = 'PUBLISHED'"), postgresql_where=sa.text("is_default IS TRUE AND is_active IS TRUE AND status = 'PUBLISHED'"))
    op.drop_index(op.f('ix_configuration_versions_status'), table_name='configuration_versions')
    op.drop_index(op.f('ix_configuration_versions_is_active'), table_name='configuration_versions')
    op.drop_index(op.f('ix_configuration_versions_equipment_model_id'), table_name='configuration_versions')
    op.drop_table('configuration_versions')
    op.drop_index(op.f('ix_warehouses_is_active'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_spare_parts_is_active'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_code'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_parts_is_active'), table_name='parts')
    op.drop_index(op.f('ix_parts_code'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_equipment_models_is_active'), table_name='equipment_models')
    op.drop_index(op.f('ix_equipment_models_code'), table_name='equipment_models')
    op.drop_table('equipment_models')
    # ### end Alembic commands ###
