<template>
  <div v-if="open" class="report-generation-dialog" role="dialog" aria-modal="true" :aria-label="t('maintenance.reports.createDialog.title')">
    <label>{{ t('maintenance.reports.createDialog.titleLabel') }}<input v-model.trim="title" required /></label>
    <label>{{ t('maintenance.reports.createDialog.typeLabel') }}<select v-model="reportType"><option value="">{{ t('maintenance.reports.createDialog.selectType') }}</option><option v-for="type in REPORT_TYPES" :key="type" :value="type">{{ t(`maintenance.reports.types.${type}`) }}</option></select></label>
    <fieldset><legend>{{ t('maintenance.reports.createDialog.sources') }}</legend><div v-for="(_, index) in sourceRefs" :key="index" class="report-generation-dialog__source"><select v-model="sourceRefs[index].type"><option value="">{{ t('maintenance.reports.createDialog.selectSourceType') }}</option><option v-for="type in sourceTypes" :key="type" :value="type">{{ t(`maintenance.reports.sourceTypes.${type}`) }}</option></select><input v-model.number="sourceRefs[index].id" type="number" min="1" :placeholder="t('maintenance.reports.createDialog.sourceId')" /><input v-model.trim="sourceRefs[index].version" :placeholder="t('maintenance.reports.createDialog.sourceVersion')" /><button type="button" @click="sourceRefs.splice(index, 1)" :aria-label="t('maintenance.reports.presentation.removeSource')">×</button></div><button type="button" @click="addSource">{{ t('maintenance.reports.createDialog.addSource') }}</button></fieldset>
    <details><summary>{{ t('maintenance.reports.createDialog.legacy') }}</summary><label>{{ t('maintenance.reports.presentation.sessionId') }} <input v-model.number="legacy.session_id" type="number" min="1" /></label><label>{{ t('maintenance.reports.presentation.scenarioVersionId') }} <input v-model.number="legacy.scenario_version_id" type="number" min="1" /></label><label>{{ t('maintenance.reports.presentation.calculationRunId') }} <input v-model.number="legacy.calculation_run_id" type="number" min="1" /></label><label>{{ t('maintenance.reports.presentation.reviewRunId') }} <input v-model.number="legacy.review_run_id" type="number" min="1" /></label></details>
    <p v-if="validation" role="alert">{{ t(validation) }}</p><p v-if="errorKey" role="alert">{{ t(errorKey) }}<template v-if="requestId"> {{ t('maintenance.reports.errors.requestId', { requestId }) }}</template></p>
    <button type="button" :disabled="submitting" @click="submit">{{ t('maintenance.reports.actions.create') }}</button><button type="button" :disabled="submitting" @click="emit('close')">{{ t('maintenance.reports.actions.cancel') }}</button>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { normalizeMaintenanceError } from '@/api/maintenance/client'
import { reportApi } from '@/api/maintenance/reports'
import { reportErrorMessageKey } from './report-actions'
import { hasValidReportSourcePolicy, REPORT_TYPES, type PublicReportSourceType, type ReportSourceReference, type ReportType } from './report-types'
const props = defineProps<{ open: boolean; refresh: () => Promise<void> }>(); const emit = defineEmits<{ (event: 'close'): void }>(); const { t } = useI18n(); const title = ref(''); const reportType = ref<ReportType | ''>(''); const sourceRefs = ref<Array<ReportSourceReference & { version: string }>>([]); const legacy = ref({ session_id: undefined as number | undefined, scenario_version_id: undefined as number | undefined, calculation_run_id: undefined as number | undefined, review_run_id: undefined as number | undefined }); const submitting = ref(false); const validation = ref(''); const errorKey = ref(''); const requestId = ref('')
const sourceTypes: readonly PublicReportSourceType[] = ['AI_SESSION', 'SCENARIO_VERSION', 'CALCULATION_RUN', 'CALCULATION_GROUP', 'DEMAND_LIST', 'DEMAND_REVIEW', 'ALLOCATION_PLAN', 'INVENTORY_STOCKTAKE']
function addSource(): void { sourceRefs.value.push({ type: '', id: 0, version: '' }) }
function validSource(source: ReportSourceReference & { version: string }): boolean { return sourceTypes.includes(source.type as PublicReportSourceType) && Number.isInteger(source.id) && source.id > 0 && source.version.trim().length > 0 }
async function submit(): Promise<void> { validation.value = ''; errorKey.value = ''; requestId.value = ''; if (!title.value || !reportType.value || !sourceRefs.value.every(validSource) || !hasValidReportSourcePolicy(reportType.value, sourceRefs.value)) { validation.value = 'maintenance.reports.createDialog.invalid'; return } submitting.value = true; try { await reportApi.createReportJob({ title: title.value, report_type: reportType.value, source_refs: sourceRefs.value.map(({ type, id, version }) => ({ type, id, version })), ...Object.fromEntries(Object.entries(legacy.value).filter(([, value]) => Number.isInteger(value) && (value as number) > 0)) }); await props.refresh(); emit('close') } catch (reason) { const error = normalizeMaintenanceError(reason); errorKey.value = reportErrorMessageKey(error.code); requestId.value = error.request_id ?? '' } finally { submitting.value = false } }
</script>
<style scoped>.report-generation-dialog { display: grid; gap: 12px; padding: 18px; border: 1px solid var(--td-component-stroke); border-radius: 8px; background: var(--td-bg-color-container); }.report-generation-dialog label, .report-generation-dialog fieldset { display: grid; gap: 6px; }.report-generation-dialog__source { display: flex; gap: 6px; }.report-generation-dialog [role="alert"] { margin: 0; color: var(--td-error-color); }</style>
