from enum import StrEnum


class SensitivityLevel(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class ProviderKind(StrEnum):
    OLLAMA = "OLLAMA"
    OPENAI_COMPATIBLE = "OPENAI_COMPATIBLE"
    DETERMINISTIC_TEST = "DETERMINISTIC_TEST"
    RULE_FALLBACK = "RULE_FALLBACK"


class ExecutionMode(StrEnum):
    LLM = "LLM"
    RULE_FALLBACK = "RULE_FALLBACK"


class ModelCapability(StrEnum):
    TEXT = "TEXT"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    STREAMING = "STREAMING"
    LONG_CONTEXT = "LONG_CONTEXT"


class ProviderHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    CONFIGURED_BUT_MODEL_MISSING = "CONFIGURED_BUT_MODEL_MISSING"


class StreamEventType(StrEnum):
    TOKEN = "TOKEN"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FieldSourceType(StrEnum):
    USER_CONFIRMED = "USER_CONFIRMED"
    USER_PROVIDED = "USER_PROVIDED"
    MASTER_DATA = "MASTER_DATA"
    KNOWLEDGE_RETRIEVED = "KNOWLEDGE_RETRIEVED"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"
    LLM_INFERRED = "LLM_INFERRED"


class FieldRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ScenarioReadiness(StrEnum):
    READY_FOR_PREVIEW = "READY_FOR_PREVIEW"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    BLOCKED = "BLOCKED"


class EvidenceType(StrEnum):
    STRUCTURED_FACT = "STRUCTURED_FACT"
    PARAMETER = "PARAMETER"
    RULE = "RULE"
    TEXT_EXCERPT = "TEXT_EXCERPT"
    CITATION = "CITATION"


class EvidenceStatus(StrEnum):
    VALID = "VALID"
    STALE = "STALE"
    CONFLICTED = "CONFLICTED"
    INCOMPLETE = "INCOMPLETE"
    UNVERIFIED = "UNVERIFIED"


class UserIntent(StrEnum):
    GENERAL_QA = "GENERAL_QA"
    SCENARIO_PARSE = "SCENARIO_PARSE"
    SCENARIO_CREATE = "SCENARIO_CREATE"
    SCENARIO_REVIEW = "SCENARIO_REVIEW"
    DEMAND_PREVIEW = "DEMAND_PREVIEW"
    DEMAND_CALCULATE = "DEMAND_CALCULATE"
    CALCULATION_EXPLAIN = "CALCULATION_EXPLAIN"
    INVENTORY_GAP_ANALYZE = "INVENTORY_GAP_ANALYZE"
    DEMAND_LIST_REVIEW = "DEMAND_LIST_REVIEW"
    MODEL_COMPARE = "MODEL_COMPARE"
    REPORT_GENERATE = "REPORT_GENERATE"
    TASK_STATUS_QUERY = "TASK_STATUS_QUERY"
    TASK_CANCEL = "TASK_CANCEL"
    SESSION_RESUME = "SESSION_RESUME"


class ConfirmationLevel(StrEnum):
    NONE = "NONE"
    IMPLICIT = "IMPLICIT"
    EXPLICIT = "EXPLICIT"
    SECONDARY = "SECONDARY"


class PlanActionType(StrEnum):
    CALL_TOOL = "CALL_TOOL"
    REQUEST_CONFIRMATION = "REQUEST_CONFIRMATION"
    RESPOND = "RESPOND"


class ReviewSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ReviewBlockingLevel(StrEnum):
    NONE = "NONE"
    BLOCK_REPORT_FINALIZATION = "BLOCK_REPORT_FINALIZATION"
    BLOCK_FORMAL_CALCULATION = "BLOCK_FORMAL_CALCULATION"
    BLOCK_SCENARIO_PUBLISH = "BLOCK_SCENARIO_PUBLISH"
