from enum import StrEnum


class ConfigurationStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class CriticalityLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReliabilityModelType(StrEnum):
    EXPONENTIAL = "EXPONENTIAL"
    WEIBULL = "WEIBULL"
    BINOMIAL = "BINOMIAL"
    NEGATIVE_BINOMIAL = "NEGATIVE_BINOMIAL"
    EMPIRICAL = "EMPIRICAL"


class DataSourceType(StrEnum):
    DESIGN_PARAMETER = "DESIGN_PARAMETER"
    MAINTENANCE_RECORD = "MAINTENANCE_RECORD"
    TEST_DATA = "TEST_DATA"
    MANUAL_ESTIMATE = "MANUAL_ESTIMATE"
    LITERATURE = "LITERATURE"
    EXPERT_JUDGMENT = "EXPERT_JUDGMENT"


class WarehouseStatus(StrEnum):
    NORMAL = "NORMAL"
    FROZEN = "FROZEN"
    COUNTING = "COUNTING"


class ImportOperation(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    UPSERT = "UPSERT"


class ScenarioVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class MissingParameterPolicy(StrEnum):
    STRICT = "STRICT"
    WARN_AND_SKIP = "WARN_AND_SKIP"
    FALLBACK = "FALLBACK"


class DemandExecutionMode(StrEnum):
    AUTO = "AUTO"
    ANALYTICAL = "ANALYTICAL"
    MONTE_CARLO = "MONTE_CARLO"
    COMPARE = "COMPARE"


class CalculationExecutionType(StrEnum):
    SYNCHRONOUS = "SYNCHRONOUS"
    ASYNCHRONOUS = "ASYNCHRONOUS"


class CalculationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"


class RerunMode(StrEnum):
    NEW = "NEW"
    REPLAY_SNAPSHOT = "REPLAY_SNAPSHOT"
    RERUN_LATEST = "RERUN_LATEST"


class AgeDistributionType(StrEnum):
    FIXED = "FIXED"
    UNIFORM = "UNIFORM"
    NORMAL = "NORMAL"
    TRIANGULAR = "TRIANGULAR"


class FailureProcessMode(StrEnum):
    AUTO = "AUTO"
    SINGLE_FAILURE = "SINGLE_FAILURE"
    RENEWAL = "RENEWAL"
    COUNT_DISTRIBUTION = "COUNT_DISTRIBUTION"


class ShockApplicationMode(StrEnum):
    FAILURE_RATE = "FAILURE_RATE"
    FAILURE_PROBABILITY = "FAILURE_PROBABILITY"
    EQUIVALENT_AGE = "EQUIVALENT_AGE"


class ItemCalculationStatus(StrEnum):
    CALCULATED = "CALCULATED"
    SKIPPED = "SKIPPED"
    FALLBACK = "FALLBACK"


class ShortageRiskLevel(StrEnum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComparisonConsistencyLevel(StrEnum):
    CONSISTENT = "CONSISTENT"
    MINOR_DEVIATION = "MINOR_DEVIATION"
    MAJOR_DEVIATION = "MAJOR_DEVIATION"


class AISessionStatus(StrEnum):
    CREATED = "CREATED"
    UNDERSTANDING = "UNDERSTANDING"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    PLANNED = "PLANNED"
    EXECUTING = "EXECUTING"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    WAITING_ASYNC_TASK = "WAITING_ASYNC_TASK"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AIMessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"
    TOOL = "TOOL"


class AIMessageType(StrEnum):
    USER_TEXT = "USER_TEXT"
    ASSISTANT_TEXT = "ASSISTANT_TEXT"
    SYSTEM_NOTICE = "SYSTEM_NOTICE"
    CLARIFICATION = "CLARIFICATION"
    CONFIRMATION_PROMPT = "CONFIRMATION_PROMPT"
    TOOL_RESULT = "TOOL_RESULT"
    ERROR_NOTICE = "ERROR_NOTICE"


class AIExecutionMode(StrEnum):
    LLM = "LLM"
    RULE_FALLBACK = "RULE_FALLBACK"


class AIPlanStatus(StrEnum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AIPlanStepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    WAITING_ASYNC_TASK = "WAITING_ASYNC_TASK"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AIToolCallStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AIConfirmationStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class AIConfirmationLevel(StrEnum):
    NONE = "NONE"
    IMPLICIT = "IMPLICIT"
    EXPLICIT = "EXPLICIT"
    SECONDARY = "SECONDARY"


class AIModelCallStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class AIEvidenceStatus(StrEnum):
    VALID = "VALID"
    STALE = "STALE"
    CONFLICTED = "CONFLICTED"
    INCOMPLETE = "INCOMPLETE"
    UNVERIFIED = "UNVERIFIED"


class AIReviewRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class AIReviewFindingStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    ACCEPTED_RISK = "ACCEPTED_RISK"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    SUPERSEDED = "SUPERSEDED"


class AISeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AIBlockingLevel(StrEnum):
    NONE = "NONE"
    BLOCK_REPORT_FINALIZATION = "BLOCK_REPORT_FINALIZATION"
    BLOCK_FORMAL_CALCULATION = "BLOCK_FORMAL_CALCULATION"
    BLOCK_SCENARIO_PUBLISH = "BLOCK_SCENARIO_PUBLISH"


class AIReportJobStatus(StrEnum):
    CREATED = "CREATED"
    BUILDING_SKELETON = "BUILDING_SKELETON"
    GENERATING_SECTIONS = "GENERATING_SECTIONS"
    VALIDATING_NUMBERS = "VALIDATING_NUMBERS"
    VALIDATING_CITATIONS = "VALIDATING_CITATIONS"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    FINALIZED = "FINALIZED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"


class AIReportVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    FINAL = "FINAL"
    SUPERSEDED = "SUPERSEDED"


class AIReportType(StrEnum):
    DEMAND_CALCULATION = "DEMAND_CALCULATION"
    INVENTORY_GAP = "INVENTORY_GAP"
    MANAGEMENT_DECISION = "MANAGEMENT_DECISION"


class AIExportFormat(StrEnum):
    MARKDOWN = "MARKDOWN"
    JSON = "JSON"
    DOCX = "DOCX"
